# -*- coding: utf-8 -*-
"""Numpy_Analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10BL_OEY-luh-vEAtX9uZg1aeRBYK1YKT
"""

import numpy as np

def welcome_menu():
    print("\nWelcome to the NumPy Analyzer!")
    print("=" * 40)
    print("Choose an option:")
    print("1. Create a Numpy Array")
    print("2. Perform Mathematical Operations")
    print("3. Combine or Split Arrays")
    print("4. Search, Sort, or Filter Arrays")
    print("5. Compute Aggregates and Statistics")
    print("6. Exit")


def create_array():
    print("\nArray Creation:")
    print("Select the type of array to create:")
    print("1. 1D Array")
    print("2. 2D Array")
    print("3. 3D Array")

    ch = int(input("Enter your choice: "))

    if ch == 1:
        n = int(input("Enter number of elements: "))
        data = list(map(int, input(f"Enter {n} elements separated by space: ").split()))
        return np.array(data)

    elif ch == 2:
        r = int(input("Enter the number of rows: "))
        c = int(input("Enter the number of columns: "))
        data = list(map(int, input(f"Enter {r+c+1} elements for the array separated by space: ").split()))
        arr = np.array(data).reshape(r, c)
        print("\nArray created successfully:")
        print(arr)
        slicing_menu(arr)
        return arr

    elif ch == 3:
        d = int(input("Enter depth: "))
        r = int(input("Enter rows: "))
        c = int(input("Enter columns: "))
        data = list(map(int, input(f"Enter {d+r+c} elements separated by space: ").split()))
        return np.array(data).reshape(d, r, c)


def slicing_menu(arr):
    print("\nChoose an operation:")
    print("1. Indexing")
    print("2. Slicing")
    print("3. Go Back")

    op = int(input("Enter your choice: "))

    if op == 2:
        rs = input("Enter the row range (start:end): ")
        cs = input("Enter the column range (start:end): ")

        r1, r2 = map(int, rs.split(":"))
        c1, c2 = map(int, cs.split(":"))

        print("\nSliced Array:")
        print(arr[r1:r2, c1:c2])


def math_operations(arr):
    print("\nMathematical Operations:")
    print("Choose a mathematical operation:")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Division")

    ch = int(input("Enter your choice: "))
    data = list(map(int, input(f"Enter the same-size array elements ({arr.size} elements separated by space): ").split()))
    arr2 = np.array(data).reshape(arr.shape)

    print("\nOriginal Array:")
    print(arr)
    print("\nSecond Array:")
    print(arr2)

    if ch == 1:
        print("\nResult of Addition:")
        print(arr + arr2)
    elif ch == 2:
        print("\nResult of Subtraction:")
        print(arr - arr2)
    elif ch == 3:
        print("\nResult of Multiplication:")
        print(arr * arr2)
    elif ch == 4:
        print("\nResult of Division:")
        print(arr / arr2)


def combine_split(arr):
    print("\nCombine or Split Arrays:")
    print("Choose an option:")
    print("1. Combine Arrays")
    print("2. Split Array")

    ch = int(input("Enter your choice: "))

    if ch == 1:
        data = list(map(int, input(f"Enter the elements of another array to combine ({arr.size} elements separated by space): ").split()))
        arr2 = np.array(data).reshape(arr.shape)

        print("\nOriginal Array:")
        print(arr)
        print("\nSecond Array:")
        print(arr2)

        print("\nCombined Array (Vertical Stack):")
        print(np.vstack((arr, arr2)))


def search_sort_filter(arr):
    print("\nSearch, Sort, and Filter:")
    print("Choose an option:")
    print("1. Search a value")
    print("2. Sort the array")
    print("3. Filter values")

    ch = int(input("Enter your choice: "))

    print("\nOriginal Array:")
    print(arr)

    if ch == 2:
        print("\nSorted Array:")
        print(np.sort(arr, axis=1))
        print("(Sorting applied row-wise.)")


def statistics(arr):
    print("\nAggregates and Statistics:")
    print("Choose an aggregate/statistical operation:")
    print("1. Sum")
    print("2. Mean")
    print("3. Median")
    print("4. Standard Deviation")
    print("5. Variance")

    ch = int(input("Enter your choice: "))

    print("\nOriginal Array:")
    print(arr)

    if ch == 3:
        print("\nMedian of Array:", np.median(arr))


def main():
    arr = None

    while True:
        welcome_menu()
        ch = int(input("Enter your choice: "))

        if ch == 1:
            arr = create_array()
        elif ch == 2:
            math_operations(arr)
        elif ch == 3:
            combine_split(arr)
        elif ch == 4:
            search_sort_filter(arr)
        elif ch == 5:
            statistics(arr)
        elif ch == 6:
            print("\nThank you for using the NumPy Analyzer! Goodbye!")
            break


main()
